name: Release on npm

on:
  push:
    paths:
      - package.json
    tags:
      - "v*"

jobs:
  build_and_publish:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test
          
      - name: Compile
        run: |
          npm run compile

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          dry-run: false

      - name: Post-publish
        if: steps.publish.outputs.type != 'none'
        run: |
          echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"

      - name: Publish skipped
        if: steps.publish.outputs.type == 'none'
        run: |
          echo "Version in package.json has not changed. Skipping."
          exit 0

      - name: Generate changelog
        id: github_release_changelog
        if: steps.publish.outputs.type != 'none'
        run: |      
          npx auto-changelog --template keepachangelog --output CHANGELOG.md --starting-version v${{ steps.publish.outputs.version }}
          cat CHANGELOG.md


      - name: Create release
        id: create_release
        if: steps.publish.outputs.type != 'none'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          release_name: Release v${{ steps.publish.outputs.version }}
          commitish: refs/heads/main
          body_path: ./CHANGELOG.md
          draft: false
          prerelease: false

